// =============================================================================

export const FETCH_AUTH = "app/FETCH_AUTH";

// =============================================================================

// Shape

export const CREATE_SHAPE = "app/CREATE_SHAPE";
export const CREATE_SHAPE_SUCCESS = "app/CREATE_SHAPE_SUCCESS";
export const DELETE_SHAPE = "app/DELETE_SHAPE";
export const DELETE_SHAPE_SUCCESS = "app/DELETE_SHAPE_SUCCESS";

export const SEARCH_SHAPES = "app/SEARCH_SHAPES";
export const SEARCH_SHAPES_SUCCESS = "app/SEARCH_SHAPES_SUCCESS";

export const LOAD_SHAPE = "app/LOAD_SHAPE";
export const LOAD_SHAPE_SUCCESS = "app/LOAD_SHAPE_SUCCESS";

export const UPDATE_SHAPE = "app/UPDATE_SHAPE";
export const UPDATE_SHAPE_SUCCESS = "app/UPDATE_SHAPE_SUCCESS";

export const CLEAR_CURRENT_SHAPE = "app/CLEAR_CURRENT_SHAPE";

export const UPDATE_SHAPE_FILTERS = "app/UPDATE_SHAPE_FILTERS";
export const RESET_SHAPE_FILTERS = "app/RESET_SHAPE_FILTERS";

export const UPDATE_SHAPE_COLLECTION_SETTINGS = "app/UPDATE_SHAPE_COLLECTION_SETTINGS";

// =============================================================================

// Products

export const CREATE_PRODUCT = "app/CREATE_PRODUCT";
export const CREATE_PRODUCT_SUCCESS = "app/CREATE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT = "app/DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "app/DELETE_PRODUCT_SUCCESS";

export const SEARCH_PRODUCTS = "app/SEARCH_PRODUCTS";
export const SEARCH_PRODUCTS_SUCCESS = "app/SEARCH_PRODUCTS_SUCCESS";

export const LOAD_PRODUCT = "app/LOAD_PRODUCT";
export const LOAD_PRODUCT_SUCCESS = "app/LOAD_PRODUCT_SUCCESS";

export const UPDATE_PRODUCT = "app/UPDATE_PRODUCT";
export const UPDATE_PRODUCT_SUCCESS = "app/UPDATE_PRODUCT_SUCCESS";

export const CLEAR_CURRENT_PRODUCT = "app/CLEAR_CURRENT_PRODUCT";

export const UPDATE_PRODUCT_FILTERS = "app/UPDATE_PRODUCT_FILTERS";
export const RESET_PRODUCT_FILTERS = "app/RESET_PRODUCT_FILTERS";

export const UPDATE_PRODUCT_COLLECTION_SETTINGS = "app/UPDATE_PRODUCT_COLLECTION_SETTINGS";

// =============================================================================

// Category

export const CREATE_CATEGORY = "app/CREATE_CATEGORY";
export const CREATE_CATEGORY_SUCCESS = "app/CREATE_CATEGORY_SUCCESS";
export const DELETE_CATEGORY = "app/DELETE_CATEGORY";
export const DELETE_CATEGORY_SUCCESS = "app/DELETE_CATEGORY_SUCCESS";

export const SEARCH_CATEGORIES = "app/SEARCH_CATEGORIES";
export const SEARCH_CATEGORIES_SUCCESS = "app/SEARCH_CATEGORIES_SUCCESS";

export const LOAD_CATEGORY = "app/LOAD_CATEGORY";
export const LOAD_CATEGORY_SUCCESS = "app/LOAD_CATEGORY_SUCCESS";

export const UPDATE_CATEGORY = "app/UPDATE_CATEGORY";
export const UPDATE_CATEGORY_SUCCESS = "app/UPDATE_CATEGORY_SUCCESS";

export const CLEAR_CURRENT_CATEGORY = "app/CLEAR_CURRENT_CATEGORY";

export const UPDATE_CATEGORY_COLLECTION_SETTINGS = "app/UPDATE_CATEGORY_COLLECTION_SETTINGS"

export const UPDATE_CATEGORIES_TREE = "app/UPDATE_CATEGORIES_TREE";
export const UPDATE_CATEGORIES_TREE_SELECTION = "app/UPDATE_CATEGORIES_TREE_SELECTION"

export const ADD_PARENT_CATEGORY = "app/ADD_PARENT_CATEGORY"
export const ADD_PARENT_CATEGORY_SUCCESS = "app/ADD_PARENT_CATEGORY_SUCCESS"

export const ADD_CHILD_CATEGORY = "app/ADD_CHILD_CATEGORY"
export const ADD_CHILD_CATEGORY_SUCCESS = "app/ADD_CHILD_CATEGORY_SUCCESS"

export const REMOVE_PARENT_CATEGORY = "app/REMOVE_PARENT_CATEGORY"
export const REMOVE_PARENT_CATEGORY_SUCCESS = "app/REMOVE_PARENT_CATEGORY_SUCCESS"

export const REMOVE_CHILD_CATEGORY = "app/REMOVE_CHILD_CATEGORY"
export const REMOVE_CHILD_CATEGORY_SUCCESS = "app/REMOVE_CHILD_CATEGORY_SUCCESS"

// =============================================================================

//Modals

export const SHOW_MODAL_CONFIRM_DELETE = "app/SHOW_MODAL_CONFIRM_DELETE";
export const HIDE_MODAL_CONFIRM_DELETE = "app/HIDE_MODAL_CONFIRM_DELETE";



